version: '3.9'

services:
  php:
    build: "docker/php81"
    restart: unless-stopped
    volumes:
      - project_data:/var/www/html
    environment:
      - APP_ENV

  nginx:
    build: "docker/nginx/symfony"
    restart: unless-stopped
    ports:
      - "8001:80"
    expose:
      - 8001
    volumes:
      - project_data:/var/www/html
    environment:
      - VIRTUAL_HOST=jobs.test,www.jobs.test
    depends_on:
      - php

volumes:
  project_data:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: ${PWD}/jobs-recruitis/
      o: bind